"""Lobby theater — open LAN now-playing lightbox on a dedicated port."""

from __future__ import annotations

DEFAULT_THEATER_PORT = 8791
POSTER_CACHE_CONTROL = "public, max-age=86400"
SSE_PING_SECONDS = 15
# Legacy default; adaptive watcher uses ACTIVE / IDLE / DEGRADED below.
WATCHER_POLL_SECONDS = 12
WATCHER_POLL_ACTIVE_SECONDS = 12
WATCHER_POLL_IDLE_SECONDS = 45
WATCHER_POLL_DEGRADED_SECONDS = 60
AVAILABLE_REFRESH_SECONDS = 180
CLIENT_SILENCE_RECONNECT_MS = 45_000

# Poster cache (process-local + DATA_DIR disk).
POSTER_NEGATIVE_TTL_SECONDS = 20 * 60
POSTER_DISK_TTL_SECONDS = 7 * 24 * 3600
POSTER_MEMORY_MAX_ENTRIES = 64
POSTER_MEMORY_MAX_BYTES = 64 * 1024 * 1024
POSTER_DISK_MAX_BYTES = 512 * 1024 * 1024
POSTER_RATE_LIMIT_PER_MINUTE = 120

__all__ = [
    "DEFAULT_THEATER_PORT",
    "POSTER_CACHE_CONTROL",
    "SSE_PING_SECONDS",
    "WATCHER_POLL_SECONDS",
    "WATCHER_POLL_ACTIVE_SECONDS",
    "WATCHER_POLL_IDLE_SECONDS",
    "WATCHER_POLL_DEGRADED_SECONDS",
    "AVAILABLE_REFRESH_SECONDS",
    "CLIENT_SILENCE_RECONNECT_MS",
    "POSTER_NEGATIVE_TTL_SECONDS",
    "POSTER_DISK_TTL_SECONDS",
    "POSTER_MEMORY_MAX_ENTRIES",
    "POSTER_MEMORY_MAX_BYTES",
    "POSTER_DISK_MAX_BYTES",
    "POSTER_RATE_LIMIT_PER_MINUTE",
]
